frr version 9.1
frr defaults traditional
hostname r3
log syslog informational
!
interface eth1
 ip address 10.0.13.2/30
 ip ospf area 0
!
interface eth2
 ip address 10.0.23.2/30
 ip ospf area 0
!
interface lo
 ip address 192.168.3.1/32
 ip ospf area 0
!
router ospf
 ospf router-id 192.168.3.1
 network 10.0.13.0/30 area 0
 network 10.0.23.0/30 area 0
 network 192.168.3.0/24 area 0
!
line vty
!
